language: node_js
node_js:
  - 10
branches:
  except:
    - gh-pages
    - l10n_develop
install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
script: if [ -z "$TRAVIS_TAG" ]; then NODE_ENV=test npm test; fi
before_deploy:
  - rm -rf node_modules
  - rm -rf frontend/node_modules
  - npm install --production
  - npm run package
after_success:
  - pip install --user awscli
  - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
  - docker build -t juice-shop .
  - docker tag juice-shop:latest 530658460091.dkr.ecr.eu-west-1.amazonaws.com/juice-shop:latest
  - docker push 530658460091.dkr.ecr.eu-west-1.amazonaws.com/juice-shop:latest

